version: '3.8'

services:
  backend:
    build: ./server
    ports:
      - "5000:5000"

  frontend:
    build: ./visgraph-app  # Путь к директории с Dockerfile для React
    ports:
      - "5001:3000"
